USE [dB NAME]
GO

SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [UniqueName] ON [BI].[ContractAccrual]
(
	[ColumnName_1] ASC,
	[ColumnName_2] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO


